name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master  # Ou master, depende do teu branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: webapp-imagens
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/webapp-imagens/image-analyzer

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy image-analyzer \
          --image gcr.io/webapp-imagens/image-analyzer \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated
