name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # ou master, conforme a sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: webapp-imagens # Certifique-se que este é o ID correto do projeto
        export_default_credentials: true

    - name: List files in workspace # Passo de debug para verificar o contexto
      run: ls -la

    - name: Build and push Docker image
      run: |
        # Explicitamente usa o diretório atual '.' como contexto.
        # Se o seu Dockerfile NÃO estiver na raiz, ajuste o caminho.
        # Ex: Se estiver em 'app/Dockerfile' e o contexto for a raiz:
        #   gcloud builds submit . --file app/Dockerfile --tag gcr.io/webapp-imagens/image-analyzer
        # Ex: Se estiver em 'app/Dockerfile' e o contexto for 'app/':
        #   gcloud builds submit ./app --tag gcr.io/webapp-imagens/image-analyzer
        gcloud builds submit . --tag gcr.io/webapp-imagens/image-analyzer

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy image-analyzer \
          --image gcr.io/webapp-imagens/image-analyzer \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated \
          --project=webapp-imagens # Adicionar o projeto explicitamente pode ajudar em alguns casos

